# Generated by Django 4.1.4 on 2023-02-22 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(default='user/post1/default.png', upload_to='Images/blogs/images/')),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_poster', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_post', to='jobs.category')),
            ],
            options={
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
